### ISSUE TITLE
Make `ws` an optional or peerDependency of mocha-remote-client

### ISSUE THREAD

**Issue by kraenhansen** [kraenhansen/mocha-remote#10]
Because [`isomorphic-ws`](http://npmjs.com/package/isomorphic-ws) only has a peerDependency on [`ws`](http://npmjs.com/package/ws) the `mocha-remote-client` should also have a peerDependency on `ws` (or perhaps just an optional dependency, in case it's installed for usage in a browser).

I noticed this when using `mocha-remote-client` in a packaged Electron app:

```
Uncaught Exception:
Error: Cannot find module 'ws'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/.../dist/mac/some.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/.../dist/mac/some.app/Contents/Resources/app.asar/node_modules/isomorphic-ws/node.js:3:18)
    at Object.<anonymous> (/.../dist/mac/some.app/Contents/Resources/app.asar/node_modules/isomorphic-ws/node.js:4:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
```

**Comment by kraenhansen** [comment]
This was fixed with v0.9.1.
